unique_ids:
  assets:
    standard-page.html: TJTX24XIX36WLKFD73BDCCIXL76MTS6I
    theme.css: HEKEDZFQXR2WK3DRUSFACZZP6B3EN372
  forms:
    Form1: CFTY7BN5LELMOSUD7DQRO7DTXDWGZNMC
  modules: {}
  scripts: {}
  server_modules: {}
